### ISSUE TITLE
Received an error that's not yet explained

### ISSUE THREAD

**Issue by hackdefendr** [logrhythm/EZ-Cloud#16]
### What happened?
I was minding my own business, when out of nowhere this error happened:

`ERROR QUERYING PERSISTENCE LAYER`

Steps to reproduce:
1. I upgraded my OC Admin v0.9.5 to OC Admin v0.9.7
2. I restarted the services where needed
3. I cleared my browser cache to be sure
4. This error keeps appearing: `Error querying persistance layer`.
5. And my previously configured Open Collectors are no longer listed.

### Copy/Paste the full error
```
ERROR QUERYING PERSISTENCE LAYER
```

### Feel free to reach me at:
You know how to reach me 👍 

### More info
Hi! Let me know which logs and from where and I will upload them.

---
Sent from "Wiki - Error Messages" template

**Comment by TonyMasse** [comment]
Thanks @hackdefendr for raising this.
It's likely a DB structure change in v0.9.7 that causes that.
"Persistence layer" is the SQL backend.
Are you deployed in Docker or Windows?

**Comment by TonyMasse** [comment]
If on Windows, did you let the "Create Database" ticked during the Install?
If not, please do it. As it will update the tables, SP and Views.
The table storing the Open Collector has been changed to store the version of Docker as well. And so are the Stored Procedures that update that table.

**Comment by hackdefendr** [comment]
Correct. We are running on Windows in a split environment.  The database and user configurations are directly on the platform manager host, and the frontend (NodeJS) is on our team jump server, both Windows Server 2019, and both on the same subnet. I am not 100% sure I ticked 'Create Database'.

**Comment by hackdefendr** [comment]
Ok I confirmed.  Every step was followed per my notes and the wiki. Still seeing the same error.

**Comment by TonyMasse** [comment]
Thanks @hackdefendr, I raised #17 to deal with the Installer apparently not updating the Table or the Stored procedure.
