### ISSUE TITLE
Received an error: "ErrorQueryingPersistanceLayer"

### ISSUE THREAD

**Issue by SpookyUSAF** [logrhythm/EZ-Cloud#38]
### What happened?
I am installing OC Admin on an OC in Open Nebula. The OC has been operational for at least one year and is successfully connected to and sending logs to an XM in Open Nebula. The install was without issue until I tried to connect to SQL.

Hostname: 172.17.5.11
MS SQL Port: 1433
Username: sa
Password: <verified to be correct in SQL Studio>

Steps to reproduce:
1. Hit save after entering info, and green bubble appears stating it was saved
2, Hit "Update Database"
3. "Error Querying Persistence Layer" appears in a red bubble

### Copy/Paste the full error
No further info is provided

### Feel free to reach me at:
robert.novak@logrhythm.com

### More info
Please contact me if you would like access to my VM(s) directly.

---
Sent from Wiki - Error Messages

**Comment by TonyMasse** [comment]
Hi @SpookyUSAF ,
`Error Querying Persistence Layer` means that the backend received an error from the SQL server.
If this happened when opening the "Update Database" page or click on the "Reload" button on the right hand side of the first card, then it's likely that your SQL server on .5.11 has a firewall up, preventing OC Admin from connecting to it, or that the IP is wrong.

I would say:
- double check you got the IP and credentials right for the SQL server
- make sure the Firewall on the XM/PM allows 1433/TCP in (it does **block** it by default)

If you are super curious and really want more info about what was wrong, you can do:
- open the Dev Tools ([F12] on a Chrome on PC, [Option] + [⌘] + [J] on Chrome on Mac)
- select Console
- See if more details are provided there
- If you want to go further, you can open the Network tab then hit the Reload button on the right hand side of the first card, then come back and look at the response from the backend API to see what caused the error.

**Comment by SpookyUSAF** [comment]
IP and credentials were verified correct usign SQL studio.
Firewall settings were double checked on Windows server and 1433 is allowed for all apps, services and networks.
When using telnet on the OC server, I can successfully connect to PM (telnet 172.17.5.11 1433) and observe packet flow in TCPDUMP on the OC.
When trying to connect to SQL in OC Admin, there is no traffic to/from 1433 observed in TCPDUMP.

**Comment by SpookyUSAF** [comment]
2023-01-18T22:18:07.911Z | VERBOSE | MS SQL is not available | Details: The "config.options.port" property must be of type number.
2023-01-18T22:18:07.911Z | WARNING | MS SQL on the XM or PM is not available (based on the current configuration), or is not yet configured in OC-Admin. Make sure to start it before the `oc-admin` container, and/or to configure it next time you login onto OC-Admin. Will try connecting again in 76 seconds.

Payload: payload: {host: "172.17.5.11", username: "sa", port: "1433", encrypt: true, isManagedOnBackend: false,…}

Port is being sent as a string instead of a number through my Chrome browser. Just posting here for context. You're using the same exact Chrome version but it's formatted as a number.

**Comment by TonyMasse** [comment]
Just did a remote session with @SpookyUSAF , and it turns out the Chrome of his test VM sends the port number of the SQL server as a string: `"1433"` instead of a number.
We tried from Chrome on his own machine, and it works just like on other machines, where the port is sent as a number.

For example, on my machine and his local machine, it looks like this:
![image](https://user-images.githubusercontent.com/50835088/213310232-5d174d14-9923-43a7-9d1c-e84448202d69.png)

On his test VM, this is what is sent:
![image](https://user-images.githubusercontent.com/50835088/213310383-7315dce7-c8cd-43e3-ab1d-cda8c1d64097.png)

Chrome versions are the same (`Version 109.0.5414.75 (Official Build) (64-bit)`).
Both systems are with US regional settings.

**Comment by TonyMasse** [comment]
Solution, implement a forced conversion in the Backend to bring the value to an integer first.

**Comment by TonyMasse** [comment]
Fixed by Commit [591d11b](https://github.com/logrhythm/EZ-Cloud/commit/591d11bb8a9499b2aa7e8cd8fb87bbbf379d50a6) in version `v1.1.1`.
