### ISSUE TITLE
Received an error: "Error Querying Persistence Layer" on initial setup

### ISSUE THREAD

**Issue by paraserv** [logrhythm/EZ-Cloud#39]
### What happened?
Fresh OC setup on CentOS 7. Followed [instructions](https://docs.logrhythm.com/docs/OCbeats/logrhythm-open-collector/open-collector-installation-and-user-guide/initialize-the-oc-admin) to install and configure oc-admin. Verified 1433 is open between OC and XM. Running Database Version Details hangs for awhile and then gives the error message briefly in red in the lower-right (before disappearing): Error Querying Persistence Layer

![Error Querying Persistence Layer](https://user-images.githubusercontent.com/6347244/217338154-d0587fae-3448-4329-8fc6-5ae491608979.jpg)

When running Update Database with sa credentials, it spins for several minutes before finally giving another quickly disappearing error message: EZ Server API returned an error. Message Code N/A Unknown error.

![EZ Server API error](https://user-images.githubusercontent.com/6347244/217339744-6c0a6a5d-c930-4a64-8852-2718f201c97c.jpg)

Checked SQL and see new EZ database, so it definitely did something and made successful connections, despite all the errors in the web ui.

Message Code:
Error Querying Persistence Layer
EZ Server API returned an error

More information available at:
https://github.com/TonyMasse/EZ-Cloud/wiki/Error-Messages#eparam
```

### Feel free to reach me at:
Nathan Church @ LogRhythm


---
Sent from Wiki - Error Messages

**Comment by paraserv** [comment]
Despite previous firewall rule validation attempts, true issue was firewall not code.

**Comment by TonyMasse** [comment]
Typical.
Been there before, all FW supposedly sorted, and one is still in the way.
Thanks for closing the Issue yourself, BTW!
