### ISSUE TITLE
[BUG] EZ Cloud API times out and causes the deployment of the pipeline to fail

### ISSUE THREAD

**Issue by RichardJamesWilliams** [logrhythm/EZ-Cloud#5]
**Describe the bug**
When deploying a pipeline to the open collector sometimes the API times out and causes it to fail.

**Error Message**
EZ Server API returned an error

**To Reproduce**
1. Create a pipeline
2. Click on deploy
3. If the API times out you get an API error returned

**Expected behavior**
Pipeline to pushed down to the Open Collector without an issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/99886384/154489095-3d15ecb9-01ab-4253-ae41-529759405f9f.png)

**Work Around**
1. Click on the return to properties button
2. Click on the + button and try to deploy again.
3. Repeat until it is successful.

**Comment by TonyMasse** [comment]
Yep, known issue.
The only fix is to increase the timeout as this step is effectively waiting for LRCTL to run a few times on the Open Collector.

I just modified the timeout from 5x 20 seconds to 5x 60 seconds.

**Comment by TonyMasse** [comment]
Done in commit [911a4c9](https://github.com/logrhythm/EZ-Cloud/commit/911a4c92c11885e0053a65fb6d0f2f4bed811eea)

Closing this issue.
