### ISSUE TITLE
[FR] Change server listener port

### ISSUE THREAD

**Issue by s3p1a** [logrhythm/EZ-Cloud#6]
I am trying to install EZ-Cloud on my platform manager (please let me know if there's a reason I shouldn't do so), and port 8400 is already bound to consul. Is there a way I can change this port?

I originally tried installing on my workstation, and it installed without error, but for some reason when I visited localhost:8400 it did not take my ezAdmin creds set during install. It didn't look like an ezAdmin was created in the PM database, though I did have connectivity to port 1433 on the PM.

**Comment by TonyMasse** [comment]
Hi @s3p1a, you can change the port of the server very easily.
1. Open the `.env` file in the root folder of the **EZ Server** service installation (typically `C:\Program Files\EZ Cloud Server\`)
2. Update (or add if missing) the following line with the preferred port:
````
PORT=8400
````
3. Restart the **EZ Server** service

**Comment by s3p1a** [comment]
Thanks Tony. It looks like that did allow me to change the port. However, it did not resolve my issue - I still cannot log in to ezCloud. When I look at my SQL server logs, I see the following error every time I try to log in:
"The prelogin packet used to open the connection is structurally invalid; the connection has been closed. Please contact the vendor of the client library. [CLIENT: 127.0.0.1]"

**Comment by s3p1a** [comment]
I fixed this issue by giving the ezCloud user the sysadmin SQL server role. Probably not ideal since the password to the account is stored in plaintext on disk but at least I'm in.
